import type { Profile } from "@/types/user";
import type { Proposal } from "@/types/proposal";
import type { Invoice } from "@/types/invoice";

export const DUMMY_PROFILE: Profile = {
  id: "user-001",
  full_name: "Sarah Müller",
  company_name: "Müller Consulting GmbH",
  email: "sarah@muellerconsulting.de",
  country_code: "DE",
  vat_number: "DE123456789",
  vat_validated: true,
  default_currency: "EUR",
  default_payment_terms: "Net 14",
  brand_color: "#2563EB",
  logo_url: null,
  stripe_account_id: "acct_1234567890",
  stripe_connected_at: "2026-01-15T10:00:00Z",
  address_line1: "Kurfürstendamm 42",
  address_line2: null,
  city: "Berlin",
  postal_code: "10707",
  invoice_prefix: "INV",
  invoice_counter: 8,
  onboarding_complete: true,
  created_at: "2026-01-01T08:00:00Z",
  updated_at: "2026-04-20T12:00:00Z",
};

export const DUMMY_PROPOSALS: Proposal[] = [
  {
    id: "prop-001",
    user_id: "user-001",
    client_name: "Thomas Weber",
    client_email: "t.weber@technova.de",
    client_company: "TechNova GmbH",
    client_vat_number: "DE987654321",
    client_country_code: "DE",
    client_address: "Unter den Linden 10, 10117 Berlin",
    title: "Go-to-Market Strategy — DACH Region",
    engagement_type: "Strategy Consulting",
    scope_summary: "3-month strategy sprint to redesign TechNova's GTM approach for the DACH region, including market analysis, positioning, and execution roadmap.",
    deliverables: [
      { item: "Market Analysis", description: "Comprehensive DACH market landscape and competitor positioning" },
      { item: "GTM Playbook", description: "Detailed go-to-market strategy document with quarterly milestones" },
      { item: "Monthly Workshops", description: "3 full-day working sessions with leadership team" },
      { item: "Execution Roadmap", description: "12-month prioritised roadmap with KPIs and success metrics" },
    ],
    timeline_start: "2026-07-01",
    timeline_end: "2026-09-30",
    timeline_notes: "Kickoff call in the first week of July",
    currency: "EUR",
    rate_type: "monthly",
    rate_amount: 8000,
    payment_structure: "retainer",
    payment_schedule: [
      { label: "Month 1", amount: 8000, due_date: "2026-07-01" },
      { label: "Month 2", amount: 8000, due_date: "2026-08-01" },
      { label: "Month 3", amount: 8000, due_date: "2026-09-01" },
    ],
    deposit_percent: 33,
    executive_summary: "TechNova GmbH faces a critical inflection point: strong product-market fit in the startup segment but limited traction with mid-market buyers across DACH. Without a coherent go-to-market strategy, growth will plateau.\n\nThis engagement delivers a comprehensive GTM redesign—from positioning and messaging to channel strategy and sales enablement. Over three months, we'll move from diagnostic to deployable playbook, giving your team the clarity and tools to capture the DACH mid-market opportunity.",
    scope_of_work: "## Deliverables\n\n| Deliverable | Description |\n|------------|-------------|\n| Market Analysis | DACH landscape, competitor positioning, buyer persona research |\n| GTM Playbook | Channel strategy, messaging framework, sales enablement |\n| Monthly Workshops | 3 full-day sessions with leadership and sales teams |\n| Execution Roadmap | 12-month prioritised plan with KPIs |\n\n## Timeline\n\nJuly 1 — September 30, 2026\n\n## What's Included\n\n- Up to 4 hours of weekly advisory calls\n- Unlimited async review of materials\n- All workshop facilitation and documentation\n- Final playbook in editable format\n\n## What's Not Included\n\n- Paid media execution or management\n- Recruitment or hiring\n- Software licensing",
    terms_and_conditions: "Payment is due within 14 days of invoice issue. Cancellation requires 14 days written notice; work completed prior to cancellation is billable. All deliverables become client property upon receipt of full payment. Both parties agree to maintain confidentiality of all shared materials for 2 years. Neither party may assign this agreement without prior written consent.",
    next_steps: "- Review and confirm this proposal by June 15\n- Pay the deposit (€2,640 incl. VAT) to secure your start date\n- Schedule kickoff call for the week of June 28\n- Share access to existing marketing materials and market research",
    original_prompt: "Proposal for TechNova GmbH. 3-month strategy consulting to redesign their GTM for DACH. Monthly workshops + weekly check-ins. €8,000/month. Starting July 2026.",
    status: "sent",
    public_token: "abc123def456ghi789jkl012",
    stripe_payment_link_id: "plink_001",
    stripe_payment_link_url: "https://buy.stripe.com/test_abc123",
    stripe_payment_intent_id: null,
    amount_paid: 0,
    pdf_url: null,
    pdf_generated_at: null,
    sent_at: "2026-05-01T09:30:00Z",
    first_opened_at: "2026-05-01T14:22:00Z",
    open_count: 3,
    signed_at: null,
    declined_at: null,
    expires_at: "2026-06-01T00:00:00Z",
    created_at: "2026-04-30T16:00:00Z",
    updated_at: "2026-05-01T09:30:00Z",
  },
  {
    id: "prop-002",
    user_id: "user-001",
    client_name: "Amélie Dupont",
    client_email: "a.dupont@growfast.fr",
    client_company: "GrowFast SAS",
    client_vat_number: "FR12345678901",
    client_country_code: "FR",
    client_address: "15 Rue du Commerce, 75015 Paris",
    title: "Leadership Development Programme",
    engagement_type: "Executive Coaching",
    scope_summary: "6-month individual executive coaching programme for the CEO, focused on scaling leadership and organisational design.",
    deliverables: [
      { item: "Bi-weekly Coaching Sessions", description: "12 x 90-minute 1:1 coaching calls" },
      { item: "Leadership Assessment", description: "360-degree feedback and strengths mapping" },
      { item: "Development Plan", description: "Personalised 6-month leadership growth roadmap" },
    ],
    timeline_start: "2026-06-01",
    timeline_end: "2026-11-30",
    timeline_notes: null,
    currency: "EUR",
    rate_type: "monthly",
    rate_amount: 3500,
    payment_structure: "retainer",
    payment_schedule: [],
    deposit_percent: 50,
    executive_summary: "Scaling from 30 to 100+ employees requires a different kind of leadership — and the transition is rarely intuitive. This programme creates the space, structure, and challenge for Amélie to develop the organisational design and delegation skills her next chapter demands.\n\nOver six months, we'll work through the specific challenges GrowFast is navigating: building management layers, maintaining culture through growth, and freeing the CEO to operate strategically rather than operationally.",
    scope_of_work: "## Deliverables\n\n- 12 x 90-minute coaching sessions (bi-weekly)\n- Leadership 360 assessment with structured feedback\n- Personalised development plan\n- Unlimited async support via WhatsApp/email\n\n## Timeline\n\nJune 1 — November 30, 2026\n\n## What's Included\n\n- All session preparation and follow-up notes\n- Curated reading and resource recommendations\n- One stakeholder interview (optional)\n\n## What's Not Included\n\n- Team coaching or group workshops\n- HR advisory or recruitment support",
    terms_and_conditions: "Monthly payments due on the 1st of each month. 14-day cancellation notice required. All session content is strictly confidential. Deliverables include session notes and the development plan, which become client property upon payment.",
    next_steps: "- Confirm engagement by May 20\n- Complete the onboarding questionnaire (sent separately)\n- Schedule the Leadership Assessment call for week of June 2\n- Pay first month deposit to confirm start date",
    original_prompt: "6 month executive coaching for GrowFast CEO, Amelie. Bi-weekly sessions. €3,500/month. Start June.",
    status: "viewed",
    public_token: "mno345pqr678stu901vwx234",
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    stripe_payment_intent_id: null,
    amount_paid: 0,
    pdf_url: null,
    pdf_generated_at: null,
    sent_at: "2026-04-28T11:00:00Z",
    first_opened_at: "2026-04-29T09:15:00Z",
    open_count: 2,
    signed_at: null,
    declined_at: null,
    expires_at: null,
    created_at: "2026-04-27T15:00:00Z",
    updated_at: "2026-04-29T09:15:00Z",
  },
  {
    id: "prop-003",
    user_id: "user-001",
    client_name: "Lars Eriksson",
    client_email: "lars@nordiklabs.se",
    client_company: "Nordik Labs AB",
    client_vat_number: null,
    client_country_code: "SE",
    client_address: "Kungsgatan 8, 111 43 Stockholm",
    title: "Product Strategy Half-Day Workshop",
    engagement_type: "Workshop",
    scope_summary: "Intensive half-day product strategy workshop for the leadership team to align on roadmap priorities and product vision.",
    deliverables: [
      { item: "Workshop Facilitation", description: "4-hour facilitated session with leadership team" },
      { item: "Pre-work Materials", description: "Diagnostic questionnaire and reading list" },
      { item: "Summary Report", description: "Key decisions, action items, and follow-up recommendations" },
    ],
    timeline_start: "2026-05-20",
    timeline_end: "2026-05-20",
    timeline_notes: "Remote via Zoom",
    currency: "EUR",
    rate_type: "project",
    rate_amount: 2800,
    payment_structure: "one-time",
    payment_schedule: [],
    deposit_percent: 100,
    executive_summary: "Nordik Labs is at an exciting juncture — a product with clear early traction but a roadmap that needs sharper focus. This half-day workshop gives your leadership team the structured space to resolve the key strategic questions that are slowing execution.\n\nBy the end of the session, you will have aligned product vision, a prioritised roadmap for Q3–Q4, and a shared decision framework for future trade-offs.",
    scope_of_work: "## Deliverables\n\n- 4-hour facilitated workshop (remote)\n- Pre-workshop diagnostic and alignment survey\n- Structured agenda and facilitation materials\n- Post-session summary with action items\n\n## Timeline\n\nMay 20, 2026\n\n## What's Included\n\n- Pre-call (30 min) with Lars to tailor the agenda\n- All facilitation materials\n- Written summary within 48 hours\n\n## What's Not Included\n\n- Follow-up implementation support\n- Additional workshops or sessions",
    terms_and_conditions: "Full payment due 7 days before the workshop date. Cancellation within 48 hours of the session forfeits the full fee. All materials become client property upon payment.",
    next_steps: "- Confirm by May 10\n- Pay in full to reserve the date\n- Complete the pre-workshop questionnaire by May 17\n- Join the 30-minute pre-call on May 18",
    original_prompt: "Half-day product strategy workshop for Nordik Labs team. Remote. €2,800 flat. May 20.",
    status: "signed",
    public_token: "yz567abc890def123ghi456j",
    stripe_payment_link_id: "plink_003",
    stripe_payment_link_url: "https://buy.stripe.com/test_xyz789",
    stripe_payment_intent_id: "pi_001",
    amount_paid: 2800,
    pdf_url: null,
    pdf_generated_at: null,
    sent_at: "2026-04-15T10:00:00Z",
    first_opened_at: "2026-04-15T10:45:00Z",
    open_count: 5,
    signed_at: "2026-04-16T14:30:00Z",
    declined_at: null,
    expires_at: null,
    created_at: "2026-04-14T09:00:00Z",
    updated_at: "2026-04-16T14:30:00Z",
  },
  {
    id: "prop-004",
    user_id: "user-001",
    client_name: "Marco Rossi",
    client_email: "marco@velogroup.it",
    client_company: "Velo Group SpA",
    client_vat_number: "IT12345678901",
    client_country_code: "IT",
    client_address: "Via Montenapoleone 12, 20121 Milano",
    title: "Organisational Design Review",
    engagement_type: "Strategy Consulting",
    scope_summary: "2-month organisational structure review and redesign for a 60-person company preparing for Series B.",
    deliverables: [
      { item: "Current State Analysis", description: "Org structure audit and gap analysis" },
      { item: "Future State Design", description: "Recommended org structure for 100+ headcount" },
      { item: "Implementation Roadmap", description: "Phased transition plan with role definitions" },
    ],
    timeline_start: "2026-06-15",
    timeline_end: "2026-08-15",
    timeline_notes: null,
    currency: "EUR",
    rate_type: "project",
    rate_amount: 14000,
    payment_structure: "milestone",
    payment_schedule: [
      { label: "Project Start (50%)", amount: 7000, due_date: "2026-06-15" },
      { label: "Completion (50%)", amount: 7000, due_date: "2026-08-15" },
    ],
    deposit_percent: 50,
    executive_summary: "Velo Group faces the classic Series B challenge: a structure that worked at 30 people is creating friction at 60 and will break at 100. Without a deliberate redesign, the organisational drag will slow hiring, dilute accountability, and frustrate your best people.\n\nThis engagement delivers a rigorous analysis of where the current structure is creating bottlenecks, followed by a future-state design optimised for your next growth phase — and a practical roadmap to get there.",
    scope_of_work: "## Deliverables\n\n| Deliverable | Description |\n|------------|-------------|\n| Current State Analysis | 2-week diagnostic with 10–15 stakeholder interviews |\n| Org Design Principles | Agreed framework for structure decisions |\n| Future State Blueprint | Recommended org chart with role definitions |\n| Transition Roadmap | Phased 90-day implementation plan |\n\n## Timeline\n\nJune 15 — August 15, 2026\n\n## What's Included\n\n- Up to 15 stakeholder interviews\n- Two executive presentations\n- All documentation in editable formats\n\n## What's Not Included\n\n- Recruitment or headhunting\n- Compensation benchmarking\n- Legal HR advisory",
    terms_and_conditions: "50% due at project start, 50% on completion. 14-day cancellation notice required. Work completed prior to cancellation is billable at a pro-rata rate. All deliverables become client property upon final payment.",
    next_steps: "- Review and confirm by June 1\n- Pay the project start deposit (€8,330 incl. VAT)\n- Provide org chart and list of interview candidates\n- Kickoff session on June 16",
    original_prompt: "Org design review for Velo Group, 60-person Italian company. 2 months, €14k project fee, 50-50 milestones. Start mid-June.",
    status: "draft",
    public_token: "klm678nop901qrs234tuv567",
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    stripe_payment_intent_id: null,
    amount_paid: 0,
    pdf_url: null,
    pdf_generated_at: null,
    sent_at: null,
    first_opened_at: null,
    open_count: 0,
    signed_at: null,
    declined_at: null,
    expires_at: null,
    created_at: "2026-05-04T11:00:00Z",
    updated_at: "2026-05-04T11:00:00Z",
  },
  {
    id: "prop-005",
    user_id: "user-001",
    client_name: "Helena van Berg",
    client_email: "h.vanberg@pulseretech.nl",
    client_company: "PulseRe Tech B.V.",
    client_vat_number: "NL123456789B01",
    client_country_code: "NL",
    client_address: "Herengracht 182, 1016 BR Amsterdam",
    title: "Brand & Positioning Sprint",
    engagement_type: "Strategy Consulting",
    scope_summary: "Focused 6-week brand positioning and messaging sprint for a B2B SaaS company entering the UK market.",
    deliverables: [
      { item: "Positioning Document", description: "Core positioning statement and messaging hierarchy" },
      { item: "Audience Personas", description: "3 detailed ICP profiles with messaging guidance" },
      { item: "Copy Framework", description: "Messaging house with website and sales deck copy guidelines" },
    ],
    timeline_start: "2026-03-01",
    timeline_end: "2026-04-15",
    timeline_notes: null,
    currency: "EUR",
    rate_type: "project",
    rate_amount: 6500,
    payment_structure: "one-time",
    payment_schedule: [],
    deposit_percent: 50,
    executive_summary: "PulseRe Tech has a strong product and early UK traction, but the messaging isn't yet doing justice to the value. Buyers are interested but confused — the positioning needs to be sharper, more specific, and more differentiated from entrenched competitors.\n\nThis sprint delivers a clear, market-tested positioning framework and the messaging tools your team needs to go to market with confidence.",
    scope_of_work: "## Deliverables\n\nPositioning strategy, ICP personas, and messaging house.\n\n## Timeline\n\nMarch 1 — April 15, 2026\n\n## What's Included\n\n- 5 customer interviews\n- Competitor messaging analysis\n- All positioning and copy assets\n\n## What's Not Included\n\n- Design or visual identity\n- Website implementation",
    terms_and_conditions: "50% deposit upfront, 50% on delivery. Standard confidentiality applies.",
    next_steps: "- Sign and pay deposit\n- Share existing positioning materials\n- Schedule customer interview kick-off",
    original_prompt: "Brand positioning sprint for PulseRe Tech, Dutch B2B SaaS. 6 weeks, €6,500. Start March.",
    status: "declined",
    public_token: "wxy890zab123cde456fgh789",
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    stripe_payment_intent_id: null,
    amount_paid: 0,
    pdf_url: null,
    pdf_generated_at: null,
    sent_at: "2026-02-20T10:00:00Z",
    first_opened_at: "2026-02-20T16:30:00Z",
    open_count: 1,
    signed_at: null,
    declined_at: "2026-02-28T09:00:00Z",
    expires_at: null,
    created_at: "2026-02-19T09:00:00Z",
    updated_at: "2026-02-28T09:00:00Z",
  },
];

export const DUMMY_INVOICES: Invoice[] = [
  {
    id: "inv-001",
    user_id: "user-001",
    proposal_id: "prop-003",
    invoice_number: "INV-2026-007",
    client_name: "Lars Eriksson",
    client_email: "lars@nordiklabs.se",
    client_company: "Nordik Labs AB",
    client_vat_number: null,
    client_country_code: "SE",
    client_address: "Kungsgatan 8, 111 43 Stockholm",
    line_items: [
      {
        description: "Product Strategy Half-Day Workshop — May 20, 2026",
        quantity: 1,
        unit_price: 2800,
        amount: 2800,
      },
    ],
    currency: "EUR",
    subtotal: 2800,
    vat_rate: 0,
    vat_amount: 0,
    total: 2800,
    vat_scenario: "reverse_charge",
    vat_notice: "Reverse charge — VAT to be accounted for by the recipient",
    issue_date: "2026-04-16",
    due_date: "2026-04-30",
    supply_date: "2026-05-20",
    status: "paid",
    stripe_payment_link_id: "plink_inv001",
    stripe_payment_link_url: "https://buy.stripe.com/test_inv001",
    stripe_payment_intent_id: "pi_inv001",
    paid_at: "2026-04-18T11:20:00Z",
    paid_amount: 2800,
    pdf_url: null,
    pdf_generated_at: null,
    created_at: "2026-04-16T14:30:00Z",
    updated_at: "2026-04-18T11:20:00Z",
  },
  {
    id: "inv-002",
    user_id: "user-001",
    proposal_id: "prop-001",
    invoice_number: "INV-2026-008",
    client_name: "Thomas Weber",
    client_email: "t.weber@technova.de",
    client_company: "TechNova GmbH",
    client_vat_number: "DE987654321",
    client_country_code: "DE",
    client_address: "Unter den Linden 10, 10117 Berlin",
    line_items: [
      {
        description: "Go-to-Market Strategy — Month 1 of 3",
        quantity: 1,
        unit_price: 8000,
        amount: 8000,
      },
    ],
    currency: "EUR",
    subtotal: 8000,
    vat_rate: 19,
    vat_amount: 1520,
    total: 9520,
    vat_scenario: "standard",
    vat_notice: null,
    issue_date: "2026-07-01",
    due_date: "2026-07-15",
    supply_date: "2026-07-31",
    status: "unpaid",
    stripe_payment_link_id: "plink_inv002",
    stripe_payment_link_url: "https://buy.stripe.com/test_inv002",
    stripe_payment_intent_id: null,
    paid_at: null,
    paid_amount: 0,
    pdf_url: null,
    pdf_generated_at: null,
    created_at: "2026-07-01T08:00:00Z",
    updated_at: "2026-07-01T08:00:00Z",
  },
  {
    id: "inv-003",
    user_id: "user-001",
    proposal_id: "prop-002",
    invoice_number: "INV-2026-006",
    client_name: "Amélie Dupont",
    client_email: "a.dupont@growfast.fr",
    client_company: "GrowFast SAS",
    client_vat_number: "FR12345678901",
    client_country_code: "FR",
    client_address: "15 Rue du Commerce, 75015 Paris",
    line_items: [
      {
        description: "Leadership Development Programme — Month 1 of 6",
        quantity: 1,
        unit_price: 3500,
        amount: 3500,
      },
    ],
    currency: "EUR",
    subtotal: 3500,
    vat_rate: 0,
    vat_amount: 0,
    total: 3500,
    vat_scenario: "reverse_charge",
    vat_notice: "Reverse charge — VAT to be accounted for by the recipient",
    issue_date: "2026-04-01",
    due_date: "2026-04-08",
    supply_date: null,
    status: "overdue",
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    stripe_payment_intent_id: null,
    paid_at: null,
    paid_amount: 0,
    pdf_url: null,
    pdf_generated_at: null,
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-01T09:00:00Z",
  },
  {
    id: "inv-004",
    user_id: "user-001",
    proposal_id: null,
    invoice_number: "INV-2026-005",
    client_name: "Kirsten Bauer",
    client_email: "kirsten@clarity-coaching.de",
    client_company: "Clarity Coaching",
    client_vat_number: null,
    client_country_code: "DE",
    client_address: "Augustusplatz 9, 04109 Leipzig",
    line_items: [
      {
        description: "Strategy Advisory — April 2026",
        quantity: 4,
        unit_price: 1200,
        amount: 4800,
      },
    ],
    currency: "EUR",
    subtotal: 4800,
    vat_rate: 19,
    vat_amount: 912,
    total: 5712,
    vat_scenario: "standard",
    vat_notice: null,
    issue_date: "2026-04-30",
    due_date: "2026-05-14",
    supply_date: "2026-04-30",
    status: "unpaid",
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    stripe_payment_intent_id: null,
    paid_at: null,
    paid_amount: 0,
    pdf_url: null,
    pdf_generated_at: null,
    created_at: "2026-04-30T17:00:00Z",
    updated_at: "2026-04-30T17:00:00Z",
  },
  {
    id: "inv-005",
    user_id: "user-001",
    proposal_id: null,
    invoice_number: "INV-2026-004",
    client_name: "James O'Brien",
    client_email: "james@stackrise.io",
    client_company: "StackRise Ltd",
    client_vat_number: "GB123456789",
    client_country_code: "GB",
    client_address: "12 Finsbury Square, London EC2A 1AR",
    line_items: [
      {
        description: "Product & GTM Advisory — Q1 2026",
        quantity: 1,
        unit_price: 9600,
        amount: 9600,
      },
    ],
    currency: "EUR",
    subtotal: 9600,
    vat_rate: 0,
    vat_amount: 0,
    total: 9600,
    vat_scenario: "outside_scope",
    vat_notice: "Supply outside scope of VAT",
    issue_date: "2026-03-31",
    due_date: "2026-04-14",
    supply_date: "2026-03-31",
    status: "paid",
    stripe_payment_link_id: "plink_inv005",
    stripe_payment_link_url: "https://buy.stripe.com/test_inv005",
    stripe_payment_intent_id: "pi_inv005",
    paid_at: "2026-04-10T09:00:00Z",
    paid_amount: 9600,
    pdf_url: null,
    pdf_generated_at: null,
    created_at: "2026-03-31T12:00:00Z",
    updated_at: "2026-04-10T09:00:00Z",
  },
];
